---
title: "Project 4"
author: "Qichao Chen"
date: "2019/11/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Step 1 Load Data and Train-test Split
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
data <- read.csv("../data/ml-latest-small/ratings.csv")
set.seed(0)
test_idx <- sample(1:nrow(data), round(nrow(data)/5, 0))
train_idx <- setdiff(1:nrow(data), test_idx)

data_train <- data[train_idx,]
data_test <- data[test_idx,]
data_train<-data_train[,1:3]
data_test<-data_test[,1:3]
ratingmean<-c()

U <- length(unique(data$userId))
I <- length(unique(data$movieId))
```

### ALS model

```{r}
source("../lib/function.R")
for(t in 1:I)
{ratingmean[t]=mean(data_train[data_train$movieId==as.character(sort(unique(data$movieId),
                                                                       decreasing = FALSE))[t],]$rating)}
res1 <- als(max.iter = 1,feature = 2, lambda = 0.01, data=data,train=data_train, test=data_test)
save(res1, file = "../output/A3.Rdata")
```




### PMF model

```{r}
source("../lib/function.R")

pmf_result <- foreach(i = 1, .combine = rbind ) %dopar% {
    outSub <-  update_PMF(f = 5, lambdap = 0.001, lambdaq = 0.1,
                      lrate = 0.001, max.iter = 100, stopping.deriv = 0.1,
                      data = data, train = data_train, test = data_test)
    outSub
}
```



###Postprocessing based on als

```{r warning=FALSE}
library(kernlab)
source("../lib/function.R")
load('../output/A3.Rdata')

#A3 rbf kernel ridge regression
rbf<-rbfdot(sigma=0.05)
Y_kernel_rbf<-y_hat_kernel(res1[['q']],rbf,lambda=0.01, f=2,data_train = data_train,data_test = data_test)

#RMSE
true_train<-data_train[order(data_train$userId),]$rating
sqrt(sum((Y_kernel_rbf[[1]][,"rating"] - true_train)^2)/length(true_train)) 

true_test<-data_test[order(data_test$userId),]$rating
sqrt(sum((Y_kernel_rbf[[2]][,"rating"] - true_test)^2)/length(true_test)) 
```


###Postprocessing based on pmf

```{r warning=FALSE}
library(kernlab)
source("../lib/function.R")

load("../output/a2_result.Rdata")

#A2 rbf kernel ridge regression
rbf<-rbfdot(sigma=0.05)
Y_kernel_rbf<-y_hat_kernel(A2_result$q,rbf,lambda=0.01, f=5,data_train = data_train,data_test = data_test)

#RMSE
true_train<-data_train[order(data_train$userId),]$rating
sqrt(sum((Y_kernel_rbf[[1]][,"rating"] - true_train)^2)/length(true_train)) 

true_test<-data_test[order(data_test$userId),]$rating
sqrt(sum((Y_kernel_rbf[[2]][,"rating"] - true_test)^2)/length(true_test)) 
```

### CV for tune parameter, do not run!

### als CV
```{r warning=FALSE}
source("../lib/function.R")
lambda_list <- seq(0.01, 0.05, 0.04)
feature_list <- seq(2, 3, 1)
f_l <- expand.grid(feature_list, lambda_list)

als_result_summary <- array(NA, dim = c(nrow(f_l), 4)) 
run_time <- system.time(for(i in 1:nrow(f_l)){
  par <- paste("feature = ", f_l[i,1], ", lambda = ", f_l[i,2])
  cat(par, "\n")
  current_result <- cv.function(data_train, K = 5, feature = f_l[i,1], lambda = f_l[i,2])
  als_result_summary[i,] <- unlist(current_result) 
  print(als_result_summary)
  
})

save(als_result_summary, file = "../output/rmse.Rdata")
```

### pmf CV
```{r warning=FALSE}
library(parallel) # one of the core R packages
library(doParallel)

library(foreach)
library(iterators)

nCores <- detectCores()
registerDoParallel(nCores) 

f_list <- c(1, 2, 3, 4, 5, rep(5, 6), rep(10, 3), 15, 15, 20, 20)
lq_list <- c(rep(0.001, 5), 0.010, 0.100, 0.001, 0.010, 0.100, 0.001, 0.001, 0.010, 0.100, 0.010, 0.001, 0.010, 0.001)
lp_list <- c(rep(0.001, 5), 0.010, 0.100, 0.010, 0.001, 0.001, 0.100, 0.001, 0.010, 0.100, 0.010, 0.001, 0.010, 0.001)
f_ll <- cbind(f_list, lq_list, lp_list)



system.time(
pmf_result_summary <- foreach(i = 1:nrow(f_ll), .combine = rbind ) %dopar% {
    outSub <-  cv.function(data = data, dat_train = data_train, K = 5, f = f_ll[i,1], lq = f_ll[i,2], lp = f_ll[i,3], max.iter = 20, lrate = 0.001)
    outSub
}
)

save(pmf_result_summary, file = "../output/cv.Rdata")
```

###Evaluation
```{r}
t1 <- system.time(als(max.iter = 1,feature = 2, lambda = 0.01, data=data,train=data_train, test=data_test))
t2 <- system.time(foreach(i = 1, .combine = rbind ) %dopar% {
    outSub <-  update_PMF(f = 5, lambdap = 0.001, lambdaq = 0.1,
                      lrate = 0.001, max.iter = 100, stopping.deriv = 0.1,
                      data = data, train = data_train, test = data_test)
    outSub
})

t1
t2
res1$train_RMSE
res1$test_RMSE
A2_result$train_RMSE
A2_result$test_RMSE
```
